version: "3"

services:
  postgresql:
    image: sandeepjasper/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USER=
      - POSTGRESQL_PASS=
      - POSTGRESQL_DB=
    volumes:
      - "postgresql-data:/var/lib/postgresql/9.4/main"
      - "postgresql-log:/var/log/postgresql"
      - "postgresql-conf:/etc/postgresql/9.4/main"
    container_name: postgresql_container
  
volumes:
  postgresql-data:
     driver: local
  postgresql-log:
     driver: local
  postgresql-conf:
     driver: local
